import type { Product, Profile } from "./types"

// Mock seller profile
const mockSeller: Profile = {
    id: "mock-seller-id",
    email: "seller@university.edu",
    full_name: "John Doe",
    college_id: "2021CS001",
    phone: "+91 98765 43210",
    avatar_url: undefined,
    bio: "Engineering student selling quality items",
    hostel_block: "Block A",
    rating: 4.8,
    total_reviews: 24,
    is_verified_student: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
}

// Mock products with premium academic/engineering items
export const mockProducts: Product[] = [
    {
        id: "1",
        seller_id: mockSeller.id,
        title: "Scientific Calculator - Casio FX-991EX",
        description: "Advanced scientific calculator with 552 functions, natural textbook display, and spreadsheet capabilities. Perfect for engineering and science students. Includes original box and manual.",
        price: 2499,
        category: "Electronics",
        condition: "like_new",
        location: "Main Campus, Block B",
        images: [],
        status: "available",
        views: 45,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        seller: mockSeller,
    },
    {
        id: "2",
        seller_id: mockSeller.id,
        title: "Physics Textbook - Resnick & Halliday",
        description: "Fundamentals of Physics 11th Edition by Halliday, Resnick & Walker. Comprehensive physics textbook covering mechanics, thermodynamics, electromagnetism, and modern physics. Minimal highlighting, excellent condition.",
        price: 899,
        category: "Textbooks",
        condition: "good",
        location: "Library Area",
        images: [],
        status: "available",
        views: 32,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        seller: mockSeller,
    },
    {
        id: "3",
        seller_id: mockSeller.id,
        title: "Engineering Drawing Kit - Professional Set",
        description: "Complete professional drawing kit including compass set, dividers, protractor, set squares, drawing board clips, and pencils. German-made precision instruments. Ideal for mechanical and civil engineering students.",
        price: 1599,
        category: "Stationery",
        condition: "new",
        location: "Engineering Block",
        images: [],
        status: "available",
        views: 28,
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        seller: mockSeller,
    },
    {
        id: "4",
        seller_id: mockSeller.id,
        title: "Digital Oscilloscope - 100MHz Dual Channel",
        description: "Hantek DSO5102P Digital Storage Oscilloscope with 100MHz bandwidth, 1GSa/s sample rate, 7-inch TFT LCD display. Essential for electronics lab work and circuit debugging. Comes with probes and carrying case.",
        price: 12999,
        category: "Lab Equipment",
        condition: "like_new",
        location: "Electronics Lab",
        images: [],
        status: "available",
        views: 67,
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        seller: mockSeller,
    },
    {
        id: "5",
        seller_id: mockSeller.id,
        title: "Mechanical Pencil Set - Rotring 600 Series",
        description: "Premium Rotring 600 mechanical pencil set with 0.5mm and 0.7mm pencils. Full metal body with knurled grip, perfect weight balance. Includes lead refills and eraser. Professional-grade writing instruments for technical drawings.",
        price: 3499,
        category: "Stationery",
        condition: "new",
        location: "Hostel Block A",
        images: [],
        status: "available",
        views: 19,
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        seller: mockSeller,
    },
]
